# Generated by Django 5.0.7 on 2024-08-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_testuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testUser',
        ),
    ]
