# Generated by Django 3.2.7 on 2024-08-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_call_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='call_room_id',
        ),
    ]
